/**
 * Shape of `flows.catalog.json` and `flow.manifest.json` generated by `periplus build`.
 * Must track the CLI `src/manifest.ts` (the site is copied into the project and does not import the CLI).
 */
export type ScreenType =
  | "screen"
  | "loading"
  | "error"
  | "empty"
  | "modal"
  | "decision";
export type Outcome = "error" | "end";
export type FlowStatus = "active" | "wip" | "deprecated";

export interface CodeRef {
  file: string;
  symbol?: string;
  line?: number;
}

export interface Rule {
  id: string;
  summary: string;
  when?: string;
  then?: string;
  where: CodeRef[];
  verify: Array<{ test: string }>;
}

export interface Api {
  endpoint: string;
  when: string;
  effect: "read" | "write";
  where: CodeRef[];
}

export type ManifestNodeKind = "entry" | "screen" | "flow" | "outcome";
export type ManifestEdgeKind = "nav" | "entry" | "flow" | "outcome";

export interface ManifestNode {
  id: string;
  kind: ManifestNodeKind;
  label: string;
  type?: ScreenType;
  outcome?: Outcome;
  summary?: string;
  screenRef?: string;
  branchId?: string;
  docPath?: string;
  folder?: string;
  pageSlug?: string;
  targetFlowId?: string;
  targetDocumented?: boolean;
  targetProject?: string;
  wip?: boolean;
  final?: boolean;
  rules: Rule[];
  apis: Api[];
  notes: string[];
}

export interface ManifestEdge {
  id: string;
  kind: ManifestEdgeKind;
  source: string;
  target: string;
  reason: string;
  ux?: string;
}

export interface ManifestScreen {
  screenRef: string;
  title: string;
  docPath: string;
  folder: string;
  pageSlug: string;
  type: ScreenType;
  lastReviewed?: string;
  nodeIds: string[];
  body: string;
}

export interface FlowManifest {
  version: 1;
  generatedBy: "periplus";
  project: string;
  flow: {
    flowId: string;
    slug: string;
    title: string;
    domain: string;
    status: FlowStatus;
    moduleRoot: string;
    include: string[];
    lastReviewed?: string;
    owners: string[];
    watchPaths: string[];
    entry: { summary: string; productSummary?: string; triggers: CodeRef[] };
    indexPath: string;
    body: string;
  };
  screens: ManifestScreen[];
  nodes: ManifestNode[];
  edges: ManifestEdge[];
}

export interface CatalogFlow {
  flowId: string;
  slug: string;
  title: string;
  domain: string;
  status: FlowStatus;
  moduleRoot: string;
  manifestPath: string;
  screens: Array<{ screenRef: string; title: string; pageSlug: string }>;
}

export interface CatalogCrossLink {
  from: string;
  to: string;
  reasons: string[];
}

export interface FlowCatalog {
  version: 1;
  generatedBy: "periplus";
  project: string;
  domains: Array<{ id: string; label: string }>;
  flows: CatalogFlow[];
  externalFlows: Array<{
    flowId: string;
    title: string;
    project?: string;
    note?: string;
    docUrl?: string;
  }>;
  crossLinks: CatalogCrossLink[];
}
