import type { FlowManifest, ManifestEdge, ManifestNode } from "../manifest.ts";
import type { ScreenType } from "../schema.ts";

const TYPE_LABEL: Record<ScreenType, string> = {
  screen: "screen",
  loading: "loading",
  error: "error",
  empty: "empty",
  modal: "modal",
  decision: "decision",
};

function nodeLabel(node: ManifestNode | undefined, id: string): string {
  if (!node) {
    return `\`${id}\``;
  }
  if (node.kind === "entry") {
    return "Flow entry";
  }
  if (node.kind === "flow") {
    return `flow \`${node.targetFlowId}\` (${node.label}${node.targetDocumented ? "" : ", undocumented"})`;
  }
  if (node.kind === "outcome") {
    return node.outcome === "error"
      ? `ERROR — ${node.label}`
      : `END — ${node.label}`;
  }
  return `\`${node.id}\``;
}

function edgeLine(
  edge: ManifestEdge,
  byId: Map<string, ManifestNode>,
  from: "source" | "target"
): string {
  const other = from === "source" ? edge.target : edge.source;
  const arrow = from === "source" ? "→" : "←";
  return `  - ${arrow} ${nodeLabel(byId.get(other), other)} — when: ${edge.reason}${edge.ux ? ` (UX: ${edge.ux})` : ""}`;
}

/**
 * Compact context for AI: what the flow does, how screens connect (and why),
 * rules, APIs and where each doc lives. Generated; the source of truth stays in `*.periplus.ts`/`.mdx`.
 */
export function renderContext(manifest: FlowManifest): string {
  const { flow } = manifest;
  const byId = new Map(manifest.nodes.map((node) => [node.id, node]));
  const screenNodes = manifest.nodes.filter((node) => node.kind === "screen");
  const lines: string[] = [];

  lines.push(`# Flow: ${flow.title}`);
  lines.push("");
  lines.push(
    "<!-- AUTO-GENERATED by periplus — do not edit. Source: index.mdx + colocated *.periplus.ts. -->"
  );
  lines.push("");
  lines.push(`- flowId: \`${flow.flowId}\``);
  lines.push(`- project: ${manifest.project}`);
  lines.push(
    `- domain: ${flow.domain} · status: ${flow.status}${flow.lastReviewed ? ` · reviewed ${flow.lastReviewed}` : ""}`
  );
  lines.push(
    `- code: \`${flow.moduleRoot}\`${flow.include.length ? ` (+ ${flow.include.map((p) => `\`${p}\``).join(", ")})` : ""}`
  );
  lines.push(`- root doc: \`${flow.indexPath}\``);
  lines.push("");

  lines.push("## Goal and entry");
  lines.push("");
  lines.push(flow.entry.summary);
  if (flow.entry.productSummary) {
    lines.push("");
    lines.push(`Product summary: ${flow.entry.productSummary}`);
  }
  if (flow.entry.triggers.length) {
    lines.push("");
    lines.push("Entry points in code:");
    for (const trigger of flow.entry.triggers) {
      lines.push(
        `- \`${trigger.file}\`${trigger.symbol ? ` · ${trigger.symbol}` : ""}`
      );
    }
  }
  lines.push("");

  lines.push(
    `## Map (${screenNodes.length} nodes, ${manifest.edges.length} links)`
  );
  lines.push("");
  lines.push(
    "Each node is `Screen:branch`. Links only come from what developers declared in `outgoing`/`incoming`."
  );
  lines.push("");

  for (const edge of manifest.edges.filter((e) => e.source === "flow:entry")) {
    lines.push(`- Entry → \`${edge.target}\` — when: ${edge.reason}`);
  }
  lines.push("");

  for (const node of screenNodes) {
    lines.push(
      `### \`${node.id}\` — ${node.label} (${TYPE_LABEL[node.type ?? "screen"]})${node.final ? " [FINAL]" : ""}${node.wip ? " [WIP]" : ""}`
    );
    lines.push("");
    lines.push(`Doc: \`${node.docPath}\` · code: \`${node.folder}\``);
    if (node.summary) {
      lines.push("");
      lines.push(node.summary);
    }

    const incoming = manifest.edges.filter((edge) => edge.target === node.id);
    const outgoing = manifest.edges.filter((edge) => edge.source === node.id);

    if (incoming.length) {
      lines.push("");
      lines.push("Comes from:");
      for (const edge of incoming) {
        lines.push(edgeLine(edge, byId, "target"));
      }
    }
    if (outgoing.length) {
      lines.push("");
      lines.push("Goes to:");
      for (const edge of outgoing) {
        lines.push(edgeLine(edge, byId, "source"));
      }
    }

    if (node.apis.length) {
      lines.push("");
      lines.push("APIs:");
      for (const api of node.apis) {
        lines.push(
          `  - \`${api.endpoint}\` (${api.effect === "read" ? "reads" : "writes"}) — ${api.when}`
        );
      }
    }

    if (node.rules.length) {
      lines.push("");
      lines.push("Rules:");
      for (const rule of node.rules) {
        const parts = [rule.summary];
        if (rule.when) {
          parts.push(`WHEN ${rule.when}`);
        }
        if (rule.then) {
          parts.push(`THEN ${rule.then}`);
        }
        lines.push(`  - [${rule.id}] ${parts.join(" · ")}`);
        const refs = [
          ...rule.where.map(
            (w) => `${w.file}${w.symbol ? `#${w.symbol}` : ""}`
          ),
          ...rule.verify.map((v) => `test: ${v.test}`),
        ];
        if (refs.length) {
          lines.push(`    - ${refs.join(" · ")}`);
        }
      }
    }

    if (node.notes.length) {
      lines.push("");
      lines.push("Notes:");
      for (const note of node.notes) {
        lines.push(`  - ${note}`);
      }
    }
    lines.push("");
  }

  const apis = new Map<string, { effect: string; nodes: string[] }>();
  for (const node of screenNodes) {
    for (const api of node.apis) {
      const entry = apis.get(api.endpoint) ?? { effect: api.effect, nodes: [] };
      if (!entry.nodes.includes(node.id)) {
        entry.nodes.push(node.id);
      }
      if (api.effect === "write") {
        entry.effect = "write";
      }
      apis.set(api.endpoint, entry);
    }
  }

  if (apis.size) {
    lines.push("## Flow APIs");
    lines.push("");
    for (const [endpoint, info] of [...apis.entries()].sort(([a], [b]) =>
      a.localeCompare(b)
    )) {
      lines.push(
        `- \`${endpoint}\` (${info.effect === "read" ? "reads" : "writes"}) — ${info.nodes.map((n) => `\`${n}\``).join(", ")}`
      );
    }
    lines.push("");
  }

  const externals = manifest.nodes.filter((node) => node.kind === "flow");
  if (externals.length) {
    lines.push("## Connected flows");
    lines.push("");
    for (const node of externals) {
      lines.push(
        `- \`${node.targetFlowId}\` — ${node.label}${node.targetDocumented ? "" : " (no periplus doc)"}${node.targetProject && node.targetProject !== manifest.project ? ` · project ${node.targetProject}` : ""}`
      );
    }
    lines.push("");
  }

  if (flow.body) {
    lines.push("## Narrative (index.mdx)");
    lines.push("");
    lines.push(flow.body);
    lines.push("");
  }

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}
