import type { FlowManifest, ManifestNode } from "../manifest.ts";

function mermaidId(id: string): string {
  return `n_${id.replace(/[^A-Za-z0-9]/g, "_")}`;
}

function escape(text: string): string {
  return text.replace(/"/g, "'").replace(/[\r\n]+/g, " ");
}

function shape(node: ManifestNode): string {
  const label = escape(
    node.kind === "screen" ? `${node.label}<br/>${node.id}` : node.label
  );
  const id = mermaidId(node.id);
  switch (node.kind) {
    case "entry":
      return `${id}(["${label}"])`;
    case "flow":
      return `${id}[["${label}"]]`;
    case "outcome":
      return `${id}(("${label}"))`;
    default:
      return node.type === "decision"
        ? `${id}{"${label}"}`
        : `${id}["${label}"]`;
  }
}

/** Static export of the same graph rendered by React Flow (handy in PRs and wikis). */
export function renderMermaid(manifest: FlowManifest): string {
  const lines = ["%% AUTO-GENERATED by periplus", "flowchart LR"];
  for (const node of manifest.nodes) {
    lines.push(`  ${shape(node)}`);
  }
  for (const edge of manifest.edges) {
    const arrow = edge.kind === "outcome" ? "-.->" : "-->";
    lines.push(
      `  ${mermaidId(edge.source)} ${arrow}|"${escape(edge.reason)}"| ${mermaidId(edge.target)}`
    );
  }
  return `${lines.join("\n")}\n`;
}
