import { pascal } from "../fsutil.ts";
import type { FlowCatalog, FlowManifest } from "../manifest.ts";
import { API_EFFECTS, OUTCOMES, SCREEN_TYPES } from "../schema.ts";

const HEADER =
  "/* eslint-disable */\n// AUTO-GENERATED by periplus — do not edit. Run `periplus build` (or `dev`).\n";

const q = (value: string) => JSON.stringify(value);

function union(values: string[]): string {
  if (!values.length) {
    return "never";
  }
  return values.map((v) => `\n  | ${q(v)}`).join("");
}

export function flowTypeNames(flowId: string) {
  const base = pascal(flowId);
  return {
    nodeId: `${base}NodeId`,
    linkTarget: `${base}LinkTarget`,
    nodes: `${flowId.toUpperCase()}_NODES`,
  };
}

export function renderFlowTypes(manifest: FlowManifest): string {
  const names = flowTypeNames(manifest.flow.flowId);
  const screenNodes = manifest.nodes.filter((node) => node.kind === "screen");
  const shortRefs = screenNodes
    .filter((node) => node.branchId === "default")
    .map((node) => node.screenRef ?? "");

  const entries = screenNodes
    .map(
      (node) =>
        `  ${q(node.id)}: {\n` +
        `    label: ${q(node.label)},\n` +
        `    type: ${q(node.type ?? "screen")},\n` +
        `    screenRef: ${q(node.screenRef ?? "")},\n` +
        `    branchId: ${q(node.branchId ?? "")},\n` +
        `    docPath: ${q(node.docPath ?? "")},\n` +
        "  },"
    )
    .join("\n");

  return `${HEADER}import type { FlowId, FlowNodeMeta } from '../../generated/+flows.catalog';
import type { PeriplusScreenDoc } from '../../generated/+periplus.types';

/** Id of this flow, as declared in its \`index.mdx\`. */
export const FLOW_ID = ${q(manifest.flow.flowId)} as const;

/** Every node documented in this flow, as \`Screen:branch\`. */
export type ${names.nodeId} =${union(screenNodes.map((node) => node.id))};

/**
 * Valid values for \`to\` / \`from\` in this flow's screen docs: \`Screen\` (shorthand for \`Screen:default\`),
 * \`Screen:branch\`, \`flow:entry\` (flow entry point) and \`flow:<flowId>\` (another documented or external flow).
 */
export type ${names.linkTarget} =${union(shortRefs)}
  | ${names.nodeId}
  | 'flow:entry'
  | \`flow:\${FlowId}\`;
/** Alias of \`${names.linkTarget}\`. */
export type LinkTarget = ${names.linkTarget};

/** Type of the \`export default\` in each \`<Folder>.periplus.ts\` of this flow. */
export type ScreenDoc = PeriplusScreenDoc<typeof FLOW_ID, LinkTarget>;

/** Metadata of each node in this flow, keyed by node id. */
export const ${names.nodes} = {
${entries}
} as const satisfies Record<${names.nodeId}, FlowNodeMeta>;
`;
}

/** Generic screen doc types; they mirror the CLI \`screenDocSchema\` (Zod). */
export function renderDocTypes(): string {
  const lit = (values: readonly string[]) =>
    values.map((value) => q(value)).join(" | ");
  return `${HEADER}
/** Role of the screen/node in the journey; drives the node style on the flow graph. */
export type ScreenType = ${lit(SCREEN_TYPES)};

/**
 * Terminal exit without navigating to another screen.
 * \`error\`: failure path without a dedicated error screen (e.g. toast + goBack).
 * \`end\`: the journey stops here without pushing another screen.
 */
export type Outcome = ${lit(OUTCOMES)};

/** Whether the API call only reads server state (\`read\`) or changes it (\`write\`). */
export type ApiEffect = ${lit(API_EFFECTS)};

/** Pointer to the code that implements something, so readers can jump from the doc to the source. */
export type CodeRef = {
  /** Repo-relative path to the implementing file (e.g. \`src/modules/cart/useCart.ts\`). */
  file: string;
  /** Function, hook, component or handler name inside \`file\`. */
  symbol?: string;
  /** 1-based line hint for humans and tools; may drift, prefer \`symbol\`. */
  line?: number;
};

/** Business rule implemented by this screen; points to the code instead of duplicating its logic. */
export type Rule = {
  /** Stable snake_case id, unique within the flow; used to reference the rule from the site and PRs. */
  id: string;
  /** One-line, product-readable description of the rule. */
  summary: string;
  /** Condition that triggers the rule (e.g. "user submits the form without a saved address"). */
  when?: string;
  /** What the app does when the condition holds (navigation, API call, validation message). */
  then?: string;
  /** Code locations that implement the rule. */
  where?: CodeRef[];
  /** Tests that prove the rule; \`test\` is the test file path or test name. */
  verify?: Array<{ test: string }>;
};

/** Backend call made by this screen. */
export type Api = {
  /** HTTP method and path, e.g. \`GET /orders/{orderId}\`; path params in braces. */
  endpoint: \`\${'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'} /\${string}\`;
  /** When the request runs (on mount, on submit, on retry…). */
  when: string;
  /** Whether the call reads or writes server state. */
  effect: ApiEffect;
  /** Call sites in code (service function, hook, action). */
  where?: CodeRef[];
};

/** Edge coming into this branch from another node or flow. */
export type Incoming<Target extends string> = {
  /**
   * Source of this edge: another node in the flow (\`Screen\` = \`Screen:default\`, or \`Screen:branch\`),
   * \`flow:entry\` for the flow entry point, or \`flow:<flowId>\` for a cross-flow handoff.
   * Must match a documented \`outgoing\` on the source side, otherwise \`check\` reports \`symmetry\`.
   */
  from: Target;
  /** Business condition under which the user arrives here (product language; required). Shown on the screen page as an incoming link. */
  reason: string;
};

/**
 * Edge leaving this branch. Each exit is either a navigation (\`to\`) or a terminal outcome
 * (\`outcome\`), never both; enforced by this type, the CLI schema and \`periplus check\`.
 */
export type Outgoing<Target extends string> =
  | {
      /**
       * Destination when the app navigates to another screen or flow: \`Screen\` (= \`Screen:default\`),
       * \`Screen:branch\` or \`flow:<flowId>\`. Same vocabulary as \`Incoming.from\`.
       */
      to: Target;
      outcome?: never;
      /** Business condition that triggers this navigation (required). Becomes the edge label on the graph. */
      reason: string;
      /** What the user sees during the transition or right after landing (loading copy, animation); not a substitute for \`reason\`. */
      ux?: string;
    }
  | {
      /**
       * Terminal exit with no destination screen. \`error\`: failure path without a dedicated error screen
       * (e.g. toast + goBack). \`end\`: the journey stops on this branch. The build draws a terminal node on the graph.
       */
      outcome: Outcome;
      to?: never;
      /** Business condition that triggers this terminal exit (required). */
      reason: string;
      /** How the failure or end is presented (toast message, modal, silent dismiss); also used as the terminal node label. */
      ux?: string;
    };

/** One role of a screen in the flow. Most screens have a single \`default\` branch. */
export type Branch<Target extends string> = {
  /** camelCase id of this role; \`default\` for regular screens. The node id is \`Screen:branchId\`. */
  branchId: string;
  /** Short title shown on the graph node and the screen page. */
  label: string;
  /** Overrides the doc-level \`type\` for this branch. */
  type?: ScreenType;
  /** One or two sentences about what this branch does for the user. */
  summary?: string;
  /** Marks the branch as work in progress; the site shows a WIP badge. */
  wip?: boolean;
  /** The customer journey ends here (e.g. success, denial), even if closing the screen leads to another flow. */
  final?: boolean;
  /** Edges into this branch; declare the matching \`outgoing\` on the source doc. */
  incoming?: Array<Incoming<Target>>;
  /** Edges out of this branch; each item has either \`to\` or \`outcome\`, plus \`reason\` (and optional \`ux\`). */
  outgoing?: Array<Outgoing<Target>>;
  /** Business rules implemented by this branch. */
  rules?: Rule[];
  /** Backend calls made by this branch. */
  apis?: Api[];
  /** Short free-form notes shown on the screen page and the graph details panel. */
  notes?: string[];
};

/** Shape of the \`export default\` of a \`<Folder>.periplus.ts\` screen doc. */
export type PeriplusScreenDoc<Flow extends string, Target extends string> = {
  /** Flow this screen belongs to; must match the \`flowId\` of a \`flows/<slug>/index.mdx\`. */
  flowId: Flow;
  /** Screen name used in node ids and link refs; defaults to the folder name. */
  screenRef?: string;
  /** Human-readable title of the screen page; defaults to the branch label (single branch) or \`screenRef\`. */
  title?: string;
  /** Default role of every branch (\`screen\` when omitted). */
  type?: ScreenType;
  /** Extra repo-relative files outside the screen folder that affect its behavior; included in \`codeFingerprint\`. */
  codePaths?: string[];
  /** Roles of this screen in the flow; at least one (\`default\` for regular screens). */
  branches: [Branch<Target>, ...Array<Branch<Target>>];
  /** Date of the last review against the code (YYYY-MM-DD). Written by \`periplus stamp\`; do not edit by hand. */
  lastReviewed?: string;
  /** Hash of the screen code at the last review; \`check\` flags the doc as stale when it changes. Written by \`periplus stamp\`; do not edit by hand. */
  codeFingerprint?: string;
};
`;
}

export function renderCatalogTypes(catalog: FlowCatalog): string {
  const flows = catalog.flows
    .map(
      (flow) =>
        `  ${q(flow.flowId)}: {\n` +
        `    title: ${q(flow.title)},\n` +
        `    slug: ${q(flow.slug)},\n` +
        `    domain: ${q(flow.domain)},\n` +
        `    status: ${q(flow.status)},\n` +
        `    moduleRoot: ${q(flow.moduleRoot)},\n` +
        `    manifestPath: ${q(flow.manifestPath)},\n` +
        "  },"
    )
    .join("\n");

  const externals = catalog.externalFlows
    .map(
      (flow) =>
        `  ${q(flow.flowId)}: { title: ${q(flow.title)}, project: ${q(flow.project ?? catalog.project)} },`
    )
    .join("\n");

  return `${HEADER}
/** Summary of a documented node, as listed in each flow's \`*_NODES\` map. */
export type FlowNodeMeta = {
  /** Branch label shown on the graph node and the screen page. */
  readonly label: string;
  /** Role of the node in the journey (branch \`type\`, falling back to the doc-level \`type\`). */
  readonly type: ${SCREEN_TYPES.map((value) => q(value)).join(" | ")};
  /** Screen name (folder name unless overridden in the doc). */
  readonly screenRef: string;
  /** Role of the screen in the flow; \`default\` for regular screens. */
  readonly branchId: string;
  /** Repo-relative path to the \`<Folder>.periplus.ts\` that declares this node. */
  readonly docPath: string;
};

/** Flows documented in this repo (one \`flows/<slug>/index.mdx\` each). */
export type DocumentedFlowId =${union(catalog.flows.map((flow) => flow.flowId))};

/** Flows declared in \`externalFlows\` of \`periplus.config.json\` (not documented here, or owned by another project). */
export type ExternalFlowId =${union(catalog.externalFlows.map((flow) => flow.flowId))};

/** Any flow that can be referenced as \`flow:<flowId>\`. */
export type FlowId = DocumentedFlowId | ExternalFlowId;

/** Documented flows keyed by \`flowId\`: title, slug, domain, status, module root and manifest path. */
export const FLOWS = {
${flows}
} as const;

/** External flows keyed by \`flowId\`: title and owning project. */
export const EXTERNAL_FLOWS = {
${externals}
} as const;

/** Catalog entry of a documented flow. */
export function getFlowMeta(flowId: DocumentedFlowId) {
  return FLOWS[flowId];
}
`;
}
