import fs from "node:fs";
import path from "node:path";

import { type Ctx, fromRepoPath, toRepoPath } from "./context.ts";
import { walkFiles, writeIfChanged } from "./fsutil.ts";
import type { FlowManifest } from "./manifest.ts";

export function hubPagesDir(ctx: Ctx): string | undefined {
  if (!ctx.config.hubDir) {
    return undefined;
  }
  return fromRepoPath(ctx, `${ctx.config.hubDir}/src/content/docs/flows`);
}

function page(
  title: string,
  description: string,
  component: string,
  props: string,
  body: string
): string {
  const children = body.trim() ? `\n\n${body.trim()}\n\n` : "";
  return `---
title: ${JSON.stringify(title)}
description: ${JSON.stringify(description)}
---

{/* AUTO-GENERATED by periplus from the colocated docs — do not edit here. */}

import ${component} from '@/components/flows/${component}.astro';

<${component} ${props}>${children}</${component}>
`;
}

/**
 * Generates the Starlight pages (flow root + one per screen), copying the authored MDX bodies.
 * The site's `flows/` folder is fully generated (gitignored).
 */
export function syncHubPages(
  ctx: Ctx,
  manifests: FlowManifest[]
): { written: string[]; removed: string[] } {
  const root = hubPagesDir(ctx);
  if (!root) {
    return { written: [], removed: [] };
  }

  const expected = new Map<string, string>();

  for (const manifest of manifests) {
    const { flow } = manifest;
    const dir = path.join(root, flow.domain, flow.slug);

    expected.set(
      path.join(dir, "index.mdx"),
      page(
        flow.title,
        `Flow ${flow.domain} — ${flow.flowId}`,
        "FlowRootPage",
        `flowId="${flow.flowId}"`,
        flow.body
      )
    );

    for (const screen of manifest.screens) {
      expected.set(
        path.join(dir, `${screen.pageSlug}.mdx`),
        page(
          screen.title,
          `${flow.title} · ${screen.screenRef}`,
          "FlowScreenPage",
          `flowId="${flow.flowId}" screenRef="${screen.screenRef}"`,
          screen.body
        )
      );
    }
  }

  const written: string[] = [];
  for (const [file, content] of expected) {
    if (writeIfChanged(file, content)) {
      written.push(toRepoPath(ctx, file));
    }
  }

  const removed: string[] = [];
  for (const file of walkFiles(root, (f) => f.endsWith(".mdx"))) {
    if (!expected.has(file)) {
      fs.rmSync(file);
      removed.push(toRepoPath(ctx, file));
    }
  }

  return { written, removed };
}
